name: Update LaraDumps Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LaraDumps Version'
        required: true
        default: 'warning'
        type: string
jobs:
  UpdateReadme:
    strategy:
      fail-fast: true
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: symfony
          extensions: json, mbstring, curl, intl, zlib

      - name: üó≥Ô∏è Prepare Env
        run: |
          echo "Version: |$VERSION|"
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV
          echo "READMEBOT_KEY=${{secrets.READMEBOT_KEY}}" >> $GITHUB_ENV
        env:
          VERSION: ${{inputs.version}}

      - name: ‚¨áÔ∏è Downloading ReadmeBot
        run: |
          wget -O readmebot "https://github.com/laradumps/readmebot/blob/main/.github/readmebot?raw=true"

      - name: üå± ReadmeBot Version
        run: |
          php readmebot --version

      - name: ü§ñ Run ReadmeBot
        run: |
          php readmebot update-version --new-version='${{env.NEW_VERSION}}' --github-credential='{"name":"${{secrets.READMEBOT_GIT_USER}}","email":"${{secrets.READMEBOT_GIT_EMAIL}}"}'
